# AlexNet Model

Importing libraries

In [1]:
import os
import cv2
import shutil
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from distutils.dir_util import copy_tree

test/train directories

In [2]:
test_dir1  = '/Users/rishabhhandoo/Documents/Coding/ML/random_stuff/dataset training/malyakew dataset/MK/D1/test' 
train_dir1 = '/Users/rishabhhandoo/Documents/Coding/ML/random_stuff/dataset training/malyakew dataset/MK/D1/train' 
test_dir2  = '/Users/rishabhhandoo/Documents/Coding/ML/random_stuff/dataset training/plant Leaves dataset/Plants_2/test'
train_dir2 = '/Users/rishabhhandoo/Documents/Coding/ML/random_stuff/dataset training/plant Leaves dataset/Plants_2/train'

In [3]:
# # data=[]

# # for categories in CATEGORIES:
# #   folder = os.path.join(DIRECTORY,categories)
# #   label=CATEGORIES.index(categories)

# #   for img in os.listdir(folder):
# #     img=os.path.join(folder,img)
# #     #img_arr=cv2.imread(img)
# #     img_arr=cv2.imread(img)
# #     img_arr=cv2.resize(img_arr,(227,227))
# #     #img_arr=pre_process.flow(img_arr)
# #     #img_arr = tf.keras.applications.mobilenet.preprocess_input(img_arr)

# #     data.append([img_arr,label])
    
    
    
# data=[]

# DIRECTORIES = [train_dir1,train_dir2]


# #problem of including the ds.store file 

# # CATOGARIES = os.listdir(train_dir1)  ##ALSO DID THE SAME FOR TRAIN_DIR1 TO REMOVE .DS_STORE FILE
# # # CATOGARIES.remove(".DS_Store")
# # CATOGARIES

# # for directory in DIRECTORIES:
# #     sub_directories = os.listdir(directory)
# #     for sub_directory in sub_directories:
# #         label = sub_directories.index(sub_directory)
# #         sub_directory_path = os.path.join(directory,sub_directory)
# #         images = os.listdir(sub_directory_path)
# #         for image in images:
# #             image_path=os.path.join(sub_directory_path,image)
# #             try:
# #                 img_arr = cv2.imread(image_path)
# #                 img_arr = cv2.resize(img_arr,(227,227))
# #                 data.append([img_arr,label])
# #             except Exception as e:
# #                 print(str(e))
 
# for directory in DIRECTORIES:
#     for dirpath, dirnames, filenames in os.walk(directory):
#         for fname in filenames:
#             if fname.endswith('.jpg') or fname.endswith('.JPG'):
#                 image_path = os.path.abspath(os.path.join(dirpath, fname))
#                 image_arr = cv2.imread(image_path)
#                 image_arr = cv2.resize(image_arr,(227,227))
#                 label = os.path.basename(os.path.dirname(os.path.abspath(os.path.join(dirpath, fname))))
#                 data.append([image_arr,label])

    
    

In [4]:
training1 = [] 
directory = train_dir1
# sub_directories=os.listdir(train_dir1)

for dirpath, dirnames, filenames in os.walk(directory):
    for fname in filenames:
        if fname.endswith('.jpg') or fname.endswith('.JPG'):   ##SO AS TO NEGLECT THE .DS_STORE
            image_path = os.path.abspath(os.path.join(dirpath, fname))
            image_arr = cv2.imread(image_path)
            image_arr = cv2.resize(image_arr,(227,227))
            label = os.path.basename(os.path.dirname(os.path.abspath(os.path.join(dirpath, fname))))
            training1.append([image_arr,label])

In [5]:
x_train1=[]
y_train1=[]
for image , label in training1:
    x_train1.append(image)
    y_train1.append(label)

In [6]:
x_train1=np.array(x_train1)
x_train1.shape

(2288, 227, 227, 3)

In [7]:
y_train1=np.array(y_train1)
y_train1

array(['Class (35)', 'Class (35)', 'Class (35)', ..., 'Class (11)',
       'Class (11)', 'Class (11)'], dtype='<U10')

In [8]:
testing1=[]
directory=test_dir1
sub_directories=os.listdir(test_dir1)

for dirpath, dirnames, filenames in os.walk(directory):
    for fname in filenames:
        if fname.endswith('.jpg') or fname.endswith('.JPG'):   ##SO AS TO NEGLECT THE .DS_STORE
            image_path = os.path.abspath(os.path.join(dirpath, fname))
            image_arr = cv2.imread(image_path)
            image_arr = cv2.resize(image_arr,(227,227))
            label = os.path.basename(os.path.dirname(os.path.abspath(os.path.join(dirpath, fname))))
            testing1.append([image_arr,label])



In [9]:
x_test1=[]
y_test1=[]
for image , label in testing1:
    x_test1.append(image)
    y_test1.append(label)
    
    
x_test1 = np.array(x_test1)
y_test1 = np.array(y_test1)
    
x_test1.shape

(528, 227, 227, 3)

# for the dataset2


In [10]:
training2=[]
directory = train_dir2

for dirpath, dirnames, filenames in os.walk(directory):
    for fname in filenames:
        if fname.endswith('.jpg') or fname.endswith('.JPG'):   ##SO AS TO NEGLECT THE .DS_STORE
            image_path = os.path.abspath(os.path.join(dirpath, fname))
            image_arr = cv2.imread(image_path)
            image_arr = cv2.resize(image_arr,(227,227))
            label = os.path.basename(os.path.dirname(os.path.abspath(os.path.join(dirpath, fname))))
            training2.append([image_arr,label])

In [11]:
training2

[[array([[[44, 41, 40],
          [43, 39, 38],
          [40, 38, 37],
          ...,
          [38, 35, 37],
          [37, 35, 37],
          [35, 32, 34]],
  
         [[43, 39, 38],
          [47, 43, 42],
          [44, 42, 41],
          ...,
          [35, 32, 34],
          [36, 33, 35],
          [36, 33, 35]],
  
         [[43, 38, 40],
          [45, 43, 42],
          [43, 41, 40],
          ...,
          [32, 29, 31],
          [35, 32, 34],
          [34, 31, 33]],
  
         ...,
  
         [[19, 18, 22],
          [20, 19, 23],
          [21, 17, 22],
          ...,
          [23, 20, 22],
          [23, 21, 24],
          [23, 22, 24]],
  
         [[17, 16, 20],
          [17, 16, 20],
          [23, 19, 24],
          ...,
          [24, 21, 23],
          [25, 22, 25],
          [23, 22, 24]],
  
         [[18, 17, 21],
          [17, 16, 20],
          [22, 18, 23],
          ...,
          [24, 23, 25],
          [25, 22, 24],
          [24, 23, 25]]], dtype=u

In [12]:
x_train2=[]
y_train2=[]
for image , label in training2:
    x_train2.append(image)
    y_train2.append(label)

In [13]:
x_train2=np.array(x_train2)
y_train2=np.array(y_train2)

In [14]:
x_train2.shape

(4274, 227, 227, 3)

In [15]:
y_train2

array(['Pongamia Pinnata diseased (P7b)',
       'Pongamia Pinnata diseased (P7b)',
       'Pongamia Pinnata diseased (P7b)', ..., 'Lemon diseased (P10b)',
       'Lemon diseased (P10b)', 'Lemon diseased (P10b)'], dtype='<U33')

In [16]:
#test2 
#x_train = x_train1+2
# same for y_train
# same for test data

# testing 2

In [17]:
testing2=[]
directory = test_dir2

for dirpath, dirnames, filenames in os.walk(directory):
    for fname in filenames:
        if fname.endswith('.jpg') or fname.endswith('.JPG'):   ##SO AS TO NEGLECT THE .DS_STORE
            image_path = os.path.abspath(os.path.join(dirpath, fname))
            image_arr = cv2.imread(image_path)
            image_arr = cv2.resize(image_arr,(227,227))
            label = os.path.basename(os.path.dirname(os.path.abspath(os.path.join(dirpath, fname))))
            testing2.append([image_arr,label])



In [18]:
x_test2=[]
y_test2=[]

for image,label in testing2:
    x_test2.append(image)
    y_test2.append(label)
len(y_test2)

110

# merging the data

In [19]:
# x_train = x_train1 + x_train2
x_train=np.concatenate((x_train1, x_train2), axis=0)

In [20]:
x_train

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        ...,

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 1,  1,  1],
         [ 1,  1,  1],
         [ 1, 

In [21]:
# y_train=y_train1+y_train2
#train_data = [y_train1,y_train2]
#y_train_cat=[]
#y_train=[]
#for data in train_data:
 #   for label in data:
 #       y_train_cat.append(label)
        

#for label in y_train_cat:
 #   y_train=y_train_cat.index(label)

y_train_concat = np.concatenate((y_train1,y_train2),axis=0)
y_train_concat=y_train_concat.reshape(len(y_train_concat),1)

y_train_concat

array([['Class (35)'],
       ['Class (35)'],
       ['Class (35)'],
       ...,
       ['Lemon diseased (P10b)'],
       ['Lemon diseased (P10b)'],
       ['Lemon diseased (P10b)']], dtype='<U33')

In [22]:
from sklearn.preprocessing import OneHotEncoder
# Create an instance of the OneHotEncoder class
onehot_encoder = OneHotEncoder()

# Perform one-hot encoding on the data
y_train = onehot_encoder.fit_transform(y_train_concat)
y_train = y_train.toarray()
# Print the encoded data
print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [23]:
y_train.shape
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [24]:
# x_test = x_test1+x_test2
x_test=np.concatenate((x_test1, x_test2), axis=0)

In [25]:
# y_test = y_test1+y_test2
y_test = np.concatenate((y_test1, y_test2), axis=0)

### Classes

In [26]:
#finding the unique names inside y_train
#unique_classes = set(y_train)
#data_classes=np.array(list(unique_classes))
#data_classes.shape

# model construction

### for tqdm progress bar 

In [27]:
# !pip install -q "tqdm>=4.36.1"

import tensorflow as tf
import tensorflow_addons as tfa

from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
import tqdm

# quietly deep-reload tqdm
import sys
from IPython.lib import deepreload 

stdout = sys.stdout
sys.stdout = open('junk','w')
deepreload.reload(tqdm)
sys.stdout = stdout

tqdm.__version__

'4.64.1'

### importing libraries 

In [28]:
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout, Flatten,\
 Conv2D, MaxPooling2D,BatchNormalization

In [29]:
alexNet = Sequential()

# 1st Convolutional Layer
alexNet.add(Conv2D(filters=96, input_shape=(227,227,3), kernel_size=(11,11),
 strides=(4,4), padding='valid'))
alexNet.add(Activation('elu'))
# Batch Normalisation before passing it to the next layer
alexNet.add(BatchNormalization())
# Pooling 
alexNet.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='valid'))
alexNet.add(Dropout(0.25))

# 2nd Convolutional Layer
# alexNet.add(Conv2D(filters=256, kernel_size=(11,11), strides=(1,1), padding='valid'))
alexNet.add(Conv2D(filters=256, kernel_size=(5,5), strides=(1,1), padding='valid'))
alexNet.add(Activation('elu'))
# Batch Normalisation
alexNet.add(BatchNormalization())
# Pooling
alexNet.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='valid'))
alexNet.add(Dropout(0.25))

# 3rd Convolutional Layer
alexNet.add(Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), padding='valid'))
alexNet.add(Activation('elu'))
# Batch Normalisation
alexNet.add(BatchNormalization())

# 4th Convolutional Layer
alexNet.add(Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), padding='valid'))
alexNet.add(Activation('elu'))
# Batch Normalisation
alexNet.add(BatchNormalization())

# 5th Convolutional Layer
alexNet.add(Conv2D(filters=256, kernel_size=(3,3), strides=(1,1), padding='valid'))
alexNet.add(Activation('elu'))
# Batch Normalisation
alexNet.add(BatchNormalization())
# Pooling
alexNet.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='valid'))
alexNet.add(Dropout(0.25))

# Passing it to a dense layer
alexNet.add(Flatten())
# 1st Dense Layer
alexNet.add(Dense(4096, input_shape=(227*227*3,)))
alexNet.add(Activation('elu'))
# Batch Normalisation
alexNet.add(BatchNormalization())
# Add Dropout to prevent overfitting
alexNet.add(Dropout(0.5))


# 2nd Dense Layer
alexNet.add(Dense(4096))
alexNet.add(Activation('elu'))
# Batch Normalisation
alexNet.add(BatchNormalization())
# Add Dropout
alexNet.add(Dropout(0.5))


# 3rd Dense Layer
alexNet.add(Dense(1000))
alexNet.add(Activation('relu'))
# Add Dropout
alexNet.add(Dropout(0.4))
# Batch Normalisation
alexNet.add(BatchNormalization())

# Output Layer
alexNet.add(Dense(66))
alexNet.add(Activation('softmax'))

alexNet.summary()

Metal device set to: Apple M1 Pro


2023-01-25 20:12:47.776180: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-01-25 20:12:47.776740: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 55, 55, 96)        34944     
                                                                 
 activation (Activation)     (None, 55, 55, 96)        0         
                                                                 
 batch_normalization (BatchN  (None, 55, 55, 96)       384       
 ormalization)                                                   
                                                                 
 max_pooling2d (MaxPooling2D  (None, 27, 27, 96)       0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 27, 27, 96)        0         
                                                                 
 conv2d_1 (Conv2D)           (None, 23, 23, 256)       6

In [30]:
alexNet.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

# early stopping


In [31]:
from sklearn.datasets import make_moons
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint
from matplotlib import pyplot as plt

In [32]:
# Early Stopping
es = EarlyStopping(
    monitor='val_loss',
    patience=200,
    verbose=1,
    mode=min
)

In [33]:
mc = ModelCheckpoint(
    'best_m.h5',
    monitor='val_accuracy',
    mode='max',
    verbose=0,
    save_best_only=True
)

In [36]:
# alexNet.fit(x_train,y_train,epochs=10)
tqdm_callback = tfa.callbacks.TQDMProgressBar()
alexNet.fit(
    x_train,y_train,
    epochs=10, #81 done
    verbose=0,
    callbacks=[tqdm_callback,es,mc]
)

Training:   0%|                                         0/10 ETA: ?s,  ?epochs/s

Epoch 1/10


0/206                                                                 ETA: ?s - 

Epoch 2/10


0/206                                                                 ETA: ?s - 

Epoch 3/10


0/206                                                                 ETA: ?s - 

Epoch 4/10


0/206                                                                 ETA: ?s - 

Epoch 5/10


0/206                                                                 ETA: ?s - 

Epoch 6/10


0/206                                                                 ETA: ?s - 

Epoch 7/10


0/206                                                                 ETA: ?s - 

Epoch 8/10


0/206                                                                 ETA: ?s - 

Epoch 9/10


0/206                                                                 ETA: ?s - 

Epoch 10/10


0/206                                                                 ETA: ?s - 

In [37]:
alexNet.fit(x_train,y_train,epochs=1)

206/206 [==============================] - 33s 149ms/step - loss: 0.3702 - accuracy: 0.8700


In [40]:
x_train.shape

(6562, 227, 227, 3)

In [41]:
print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
